config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views

urlpatterns = [
    url(r'', include('drdown.core.urls', namespace='core')),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('drdown.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^forum/', include('drdown.forum.urls', namespace='forum')),
    url(r'^careline/', include('drdown.careline.urls', namespace='careline')),
    url(r'^medicalrecords/', include('drdown.medicalrecords.urls', namespace='medicalrecords')),
    url(r'^appointments/', include('drdown.appointments.urls', namespace='appointments')),
    url(r'^events/', include('drdown.events.urls', namespace='events')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request,
            kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied,
            kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found,
            kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

drdown/careline/urls.py
from django.conf.urls import url

from .views import (
    ChecklistDetailView,
    ChecklistRedirectView,
    ChecklistUpdateView
)

app_name = 'careline'
urlpatterns = [
    url(
        regex=r'^$',
        view=ChecklistRedirectView.as_view(),
        name='checklist_list'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=ChecklistDetailView.as_view(),
        name='checklist_detail'
    ),
    url(
        regex=r'^view/update$',
        view=ChecklistUpdateView.as_view(),
        name='checklist_update'
    ),
]

drdown/core/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView


app_name = 'core'
urlpatterns = [
    url(
        regex=r'^$',
        view=TemplateView.as_view(template_name='core/home.html'),
        name='home'
    ),
    url(
        regex=r'^info/$',
        view=TemplateView.as_view(template_name='core/info.html'),
        name='about'
    ),
    url(
        regex=r'^vaccine/$',
        view=TemplateView.as_view(template_name='core/vaccine_schedule.html'),
        name='vaccine'
    ),
    url(
       regex=r'^vaccine/location$',
       view=TemplateView.as_view(
           template_name='core/vaccination_locations.html'
        ),
       name='locations'
    ),

]

drdown/events/urls.py
from django.conf.urls import url
from drdown.events.views.view_event import EventsListView
from drdown.events.views.view_event import EventsCreateView
from drdown.events.views.view_event import EventsUpdateView
from drdown.events.views.view_event import EventsDeleteView

app_name = 'events'

urlpatterns = [
    url(
        regex=r'^$',
        view=EventsListView.as_view(),
        name='list_events'
    ),
    url(
        regex=r'^new/$',
        view=EventsCreateView.as_view(),
        name='create_event'
    ),
    url(
        regex=r'^update/(?P<pk>\d+)/$',
        view=EventsUpdateView.as_view(),
        name='update_event'
     ),
    url(
        regex=r'^delete/(?P<pk>\d+)/$',
        view=EventsDeleteView.as_view(),
        name='delete_event'
     ),

]

drdown/forum/urls.py
from django.conf.urls import url
from .views import view_category
from .views import view_commentary
from .views import view_post


app_name = 'forum'
urlpatterns = [
    url(
        regex=r'^$',
        view=view_category.CategoryListView.as_view(),
        name='list_categories'
    ),
    url(
        regex=r'^(?P<slug>[-\w]+)-(?P<pk>\d+)/$',
        view=view_post.PostListView.as_view(),
        name='list_posts'
    ),
    url(
        regex=r'^(?P<slug>[-\w]+)-(?P<pk>\d+)/new/$',
        view=view_post.PostCreateView.as_view(),
        name='create_post'
    ),
    url(
        regex=r'^(?P<slug>[-\w]+)-(?P<pk>\d+)/posts/delete/(?P<post_pk>\d+)/$',
        view=view_post.PostDeleteView.as_view(),
        name='delete_post'
    ),
    url(
        regex=r'^(?P<slug>[-\w]+)-(?P<pk>\d+)/posts/edit/(?P<post_pk>\d+)/$',
        view=view_post.PostUpdateView.as_view(),
        name='update_post'
    ),
    url(
        regex=r'^(?P<slug>[-\w]+)-(?P<pk>\d+)/posts/(?P<post_pk>\d+)/$',
        view=view_commentary.CommentaryListView.as_view(),
        name='list_commentary'
    ),
    url(
        regex=r'^(?P<slug>[-\w]+)-(?P<pk>\d+)/posts/(?P<post_pk>\d+)/new/$',
        view=view_commentary.CommentaryCreateView.as_view(),
        name='create_commentary'
    ),
    url(
        regex=r'^(?P<slug>[-\w]+)-(?P<pk>\d+)/posts/(?P<post_pk>\d+)/'
              'delete/(?P<commentary_pk>\d+)/$',
        view=view_commentary.CommentaryDeleteView.as_view(),
        name='delete_commentary'
    ),
    url(
        regex=r'^(?P<slug>[-\w]+)-(?P<pk>\d+)/posts/(?P<post_pk>\d+)/'
              'update/(?P<commentary_pk>\d+)/$',
        view=view_commentary.CommentaryUpdateView.as_view(),
        name='update_commentary'
    ),
]

drdown/users/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'users'
urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~delete/',
        view=views.UserDeleteView.as_view(),
        name='delete'
    ),
    url(
        regex=r'^~patients/$',
        view=views.PatientListViewSelector.as_view(),
        name='patient_list'
    ),
    url(
        regex=r'^~responsible/patients/$',
        view=views.ResponsiblePatientListView.as_view(),
        name='responsible_patient_list'
    ),
    url(
        regex=r'^~healthteam/patients/$',
        view=views.HealthTeamPatientListView.as_view(),
        name='healthteam_patient_list'
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

drdown/core/templates/core/403_csrf.html
{% extends "core/base.html" %}
{% load i18n %}
{% block title %}{% trans "Forbidden (403)" %}{% endblock %}

{% block content %}
<h1>{% trans "Forbidden (403)" %}</h1>

<p class="lead">{% trans "CSRF verification failed. Request aborted." %}</p>
{% endblock content %}

drdown/core/templates/core/base-nav.html
{% load static i18n %}<!DOCTYPE html>
<html lang="pt_BR">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}{% trans "Dr. Down" %}{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="EPS/MDS">

    <link rel="icon" href="{% static 'core/images/favicon.ico' %}">
    <link rel="shortcut icon" href="{% static 'core/images/favicon.ico' %}">


    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    {% block css %}

    <!-- Latest compiled and minified Bootstrap 4 beta CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

    <!-- Your stuff: Third-party CSS libraries go here -->

    <!-- Bootstrap core CSS -->
    <link href="{% static 'core/homepage/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static 'core/homepage/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <!-- Custom styles for this template -->
    <link href="{% static 'core/homepage/css/freelancer.css' %}" rel="stylesheet">
    <link href="{% static 'core/css/project.css' %}" rel="stylesheet">
    {% endblock %}

    {% block script %}
    {%  endblock %}
  </head>
  <body id="page-top">
    <!-- Navigation -->
    {% block navbar %}
    <nav class="navbar navbar-expand-lg bg-secondary fixed-top text-uppercase" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="{% url 'core:home' %}#page-top">{% trans "Dr. Down" %}</a>
        <button class="navbar-toggler mb-3 navbar-toggler-right text-uppercase btn-secondary text-white rounded border border-secondary" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          {% trans "Menu" %}
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item mx-0 mx-lg-1">
              <a class="nav-link py-3 px-0 rounded js-scroll-trigger" href="{% url 'core:home' %}#page-top"><button type="button" class="btn btn-secondary text-uppercase"><strong>{% trans "Home" %}</strong></button></a>
            </li>
            <li class="nav-item mx-0 mx-lg-1">
              <a class="nav-link py-3 px-0 rounded js-scroll-trigger" href="{% url 'core:about' %}"><button type="button" class="btn btn-secondary text-uppercase"><strong>{% trans "Down's Syndrome" %}</strong></button></a>
            </li>
            <li class="nav-item mx-0 mx-lg-1">
              <a class="nav-link py-3 px-0 rounded js-scroll-trigger" href="{% url 'forum:list_categories' %}"><button type="button" class="btn btn-secondary text-uppercase"><strong>{% trans "Forums" %}</strong></button></a>
            </li>
            {% if user.is_authenticated %}
            <div class="btn-group">
              <li class="nav-item mx-0 mx-lg-1">
                <a class="nav-link px-0 mt-2" href= "{% url 'users:detail' request.user.username %}"><button type="button" class="btn btn-secondary text-uppercase"><strong>{{request.user.username}}</strong></button></a>
              </li>

            </div>
            {% else %}
              <li class="nav-item mx-0 mx-lg-1">
                <a class="nav-link py-3 px-0 rounded js-scroll-trigger" href="{% url 'account_login' %}"><button type="button" class="btn btn-secondary text-uppercase"><strong>{% trans "Sign in" %}</strong></button></a>
              </li>
              <li class="nav-item mx-0 mx-lg-1">
                <a class="nav-link py-3 px-0 rounded js-scroll-trigger" href="{% url 'account_signup' %}"><button type="button" class="btn btn-secondary text-uppercase"><strong>{% trans "Sign up" %}</strong></button></a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    {% endblock navbar %}


    {% if messages %}
      {% for message in messages %}
          <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
      {% endfor %}
    {% endif %}


    <div class="content content-margin">
      {% block content %}
      {% endblock content %}
    </div>
        <!-- Footer -->
    <footer class="footer text-center">
      <div class="container">
       <div class="row">
          <div class="col-lg-8 mx-auto text-center">
            <h4 class="text-uppercase mb-4">CRIS DOWN</h4>
            <p class="lead">
              {% trans "Centro de Referência Interdisciplinar em Síndrome de Down" %}
              <br>{% trans "Location: HRAN - Setor Hospitalar Norte, quadra 1, bloco A, Asa Norte" %}
              <br>{% trans "Phone: 3325-4219" %}
            </p>
          </div>
        </div>
      </div>
    </footer>
    <div class="copyright py-4 text-center text-white">
      <div class="container">
        <small>{% trans "Copyright &copy; Dr. Down 2018" %}</small>
      </div>
    </div>
    <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
    <div class="scroll-to-top d-lg-none position-fixed ">
      <a class="js-scroll-trigger d-block text-center text-white rounded" href="#page-top">
        <i class="fa fa-chevron-up"></i>
      </a>
    </div>
    {% block modal %}{% endblock modal %}
    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Required by Bootstrap v4 beta -->
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->
      <!-- place project specific Javascript in this file -->
      <script src="{% static 'core/js/project.js' %}"></script>
      <script src="{% static 'core/homepage/vendor/jquery/jquery.min.js' %}"></script>
      <script src="{% static 'core/homepage/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
      <!-- Plugin JavaScript -->
      <script src="{% static 'core/homepage/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
      <!-- Custom scripts for this template -->
      <script src="{% static 'core/homepage/js/freelancer.min.js' %}"></script>
    {% endblock javascript %}
  </body>
</html>

drdown/core/templates/core/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="pt_BR">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}{% trans "Dr. Down" %}{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="EPS/MDS">

    <link rel="icon" href="{% static 'core/images/favicon.ico' %}">
    <link rel="shortcut icon" href="{% static 'core/images/favicon.ico' %}">


    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    {% block css %}

    <!-- Latest compiled and minified Bootstrap 4 beta CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

    <!-- Your stuff: Third-party CSS libraries go here -->

    <!-- Bootstrap core CSS -->
    <link href="{% static 'core/homepage/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static 'core/homepage/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <!-- Custom styles for this template -->
    <link href="{% static 'core/homepage/css/freelancer.css' %}" rel="stylesheet">
    <link href="{% static 'core/css/project.css' %}" rel="stylesheet">
    <link href="{% static 'core/css/simple-sidebar.css' %}" rel="stylesheet">
    <link href="{% static 'core/css/vaccineshedule.css' %}" rel="stylesheet">
    {% endblock %}

    {% block script %}
    {%  endblock %}
  </head>

  <body id="page-top">

    <!-- Large modal -->
    <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-lg modal-vaccine">
        <div class="modal-content">
          <div class="modal-body">
          {% include "core/vaccine_schedule.html" %}
          </div>
        </div>
      </div>
    </div>

    <!-- Navigation -->
    {% block navbar %}
    <div id="wrapper">
      <!-- Sidebar -->
      <div id="sidebar-wrapper">
        <div class="container">
          <li class="navbar-brand ml-4 list-inline"><a href="{% url 'core:home' %}">Dr. Down</a></li>
          {% if request.user.photo %}
            <img class="center" src="{{ request.user.photo.url }}" width="100px" >
          {% else %}
            <img class="center" src="{% static 'users/img/user.png' %}" width="100px" >
          {% endif %}
          <h5 class="text-primary text-center mt-2">{{request.user.username}}</h5>
        </div>

        <hr class="star">

        <ul class="sidebar-nav">

          <li><a href="{% url 'users:detail' request.user.username %}">
            {% trans "My Profile" %}
          </a></li>

          {% if not user.healthteam %}
          <li class="dropdown">
            <a href="#appointments" data-toggle="collapse" aria-expanded="false" >
              {% trans "Appointments" %}
            </a>
            <ul class="collapse list-unstyled" id="appointments" data-collapse-group="collapse-group">
              <li><a href="{% url 'appointments:list_appointments' %}">
                {% trans "Scheduled" %}
              </a></li>
              <li><a href="{% url 'appointments:list_requests' %}">
                {% trans "Requests" %}
              </a></li>
            </ul>
          </li>
          {% endif %}

          {% if user.healthteam %}
            <li><a href="{% url 'appointments:list_appointments' %}" >
              {% trans "Appointments" %}
            </a></li>
            <li><a href="{% url 'users:healthteam_patient_list' %}">
              {% trans "My Patients" %}
            </a></li>
            <li><a href="#">
              {% trans "My Schedule" %}
            </a></li>

          {% elif user.patient %}
            <li class="dropdown">
              <a href="#medicalhistory" data-toggle="collapse" aria-expanded="false" >
                {% trans "Medical History" %}
              </a>
              <ul class="collapse list-unstyled" id="medicalhistory" data-collapse-group="collapse-group">
                <li><a href="{% url 'medicalrecords:list_medicalrecords' request.user.username  %}">
                  {% trans "Medical Record" %}
                </a></li>
                <li><a href="{% url 'careline:checklist_detail' request.user.username  %}">
                  {% trans "Care Line" %}
                </a></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#vaccines-pat" data-toggle="collapse" aria-expanded="false" >
                {% trans "Vaccines" %}
              </a>
              <ul class="collapse list-unstyled" id="vaccines-pat" data-collapse-group="collapse-group">
                <li><a href=".bd-example-modal-lg" data-toggle="modal" data-target=".bd-example-modal-lg">
                  {% trans "Calendar" %}
                </a></li>
                <li><a href="{% url 'core:locations' %}">
                  {% trans "Health Centers" %}
                </a></li>
              </ul>
            </li>

          {% elif user.responsible %}
            {% for patient in request.user.responsible.patient_set.all %}
              {% if forloop.revcounter is not 1 and forloop.counter == 1%}
              <li class="dropdown">
                <a href="#patient" data-toggle="collapse" aria-expanded="false" >
                  {% trans " My Patients" %}
                </a>
                <ul class="collapse list-unstyled" id="patient" data-collapse-group="collapse-group">
                  {% for patient in request.user.responsible.patient_set.all %}
                  <li><a href="{% url 'medicalrecords:list_medicalrecords' patient.user.username  %}">
                    {{patient.user.name}}
                  </a></li>
                  {% endfor %}

                </ul>
              </li>
              {% elif forloop.revcounter ==  1  and forloop.counter == 1 %}
                  <li><a href="{% url 'medicalrecords:list_medicalrecords' patient.user.username  %}">
                    {{patient.user.name}}
                  </a></li>
              {% endif %}
            {% endfor %}
            <li class="dropdown">
              <a href="#vaccine-resp" data-toggle="collapse" aria-expanded="false" >
                {% trans "Vaccines" %}
              </a>
              <ul class="collapse list-unstyled" id="vaccine-resp" data-collapse-group="collapse-group">
                <li><a href=".bd-example-modal-lg" data-toggle="modal" data-target=".bd-example-modal-lg">
                  {% trans "Calendar" %}
                </a></li>
                <li><a href="{% url 'core:locations' %}">
                  {% trans "Health Centers" %}
                  </a></li>
              </ul>
            </li>

          {% elif user.employee %}
            <li><a href="{% url 'users:healthteam_patient_list' %}">
              {% trans "Patients" %}
            </a></li>

          {% endif %}

            <li><a href="{% url 'forum:list_categories' %}">{% trans "Forums" %}</a></li>
            <li><a href="{% url 'events:list_events' %}">{% trans "Events" %}</a></li>
            <li><a href="#">{% trans "Help" %}</a></li>
            <li><a class="text-danger" data-toggle="modal" data-target="#logout" href="">{% trans "Log out" %}</a></li>
        </ul>
      </div>

        <!-- Logout Modal -->
        <div class="modal fade" id="logout" role="dialog">
          <div class="modal-dialog modal-sm modal-dialog-centered">
            <div class="modal-content">
              <div class="modal-header">
                <h4 class="modal-title">{% trans 'Log out' %}</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
              </div>
              <div class="modal-body">
                <p>{% trans 'Are you sure you want to log out?' %}</p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">{% trans 'Cancel' %}</button>
                <form method="post" action="{% url 'account_logout' %}">
                  {% csrf_token %}
                  {% if redirect_field_value %}
                    <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
                  {% endif %}
                  <button class="btn btn-danger float-right" type="submit">{% trans 'Log Out' %}</button>
                </form>
              </div>
            </div>
          </div>
        </div>

      {% if messages %}
        {% for message in messages %}
            <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
        {% endfor %}
      {% endif %}

      <!-- Page Content -->
      <wrapper class="d-flex flex-column">
        <a href="#menu-toggle" class="btn fa fa-bars" id="menu-toggle"></a>
        <div class="flex-fill out-sidebar-content">
          {% block content %}
          {% endblock content %}
        </div>

        <!-- Footer -->
        <div class="copyright py-4 text-center text-white">
          <div class="container">
            <small>{% trans "Copyright &copy; Dr. Down 2018" %}</small>
          </div>
        </div>
      </wrapper>
    </div>
    {% endblock navbar %}




    <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
    <div class="scroll-to-top d-lg-none position-fixed ">
      <a class="js-scroll-trigger d-block text-center text-white rounded" href="#page-top">
        <i class="fa fa-chevron-up"></i>
      </a>
    </div>

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Required by Bootstrap v4 beta -->
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->
      <!-- place project specific Javascript in this file -->
      <script src="{% static 'core/homepage/vendor/jquery/jquery.min.js' %}"></script>
      <script src="{% static 'core/homepage/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
      <!-- Plugin JavaScript -->
      <script src="{% static 'core/homepage/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
      <!-- Custom scripts for this template -->
      <script src="{% static 'core/homepage/js/freelancer.min.js' %}"></script>
      <script>
        $("#menu-toggle").click(function(e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });
      </script>
      <script>
        $("[data-collapse-group]").on('show.bs.collapse', function () {
          var $this = $(this);
          var thisCollapseAttr = $this.attr('data-collapse-group');
          $("[data-collapse-group='" + thisCollapseAttr + "']").not($this).collapse('hide');
        });
      </script>
    {% endblock javascript %}
  </body>
</html>